name = "PlateTags"
uuid = "40dcd248-a7ec-4ab5-a8eb-2f5f455ac4b7"
version = "0.1.0"
authors = ["Ben David <66976120+bmdavid2@users.noreply.github.com>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
PDFmerger = "3beb2ed1-af7d-458f-b727-6e9beb3586c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QRCoders = "f42e9828-16f3-11ed-2883-9126170b272d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Measures = "0.3.3"
QRCoders = "1.4.5"
Test = "1.11.0"
UUIDs = "1.11.0"
